/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KataloqRouteImport } from './routes/kataloq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KateqoriyaSlugRouteImport } from './routes/kateqoriya.$slug'

const KataloqRoute = KataloqRouteImport.update({
  id: '/kataloq',
  path: '/kataloq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KateqoriyaSlugRoute = KateqoriyaSlugRouteImport.update({
  id: '/kateqoriya/$slug',
  path: '/kateqoriya/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kataloq': typeof KataloqRoute
  '/kateqoriya/$slug': typeof KateqoriyaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kataloq': typeof KataloqRoute
  '/kateqoriya/$slug': typeof KateqoriyaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kataloq': typeof KataloqRoute
  '/kateqoriya/$slug': typeof KateqoriyaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kataloq' | '/kateqoriya/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kataloq' | '/kateqoriya/$slug'
  id: '__root__' | '/' | '/kataloq' | '/kateqoriya/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KataloqRoute: typeof KataloqRoute
  KateqoriyaSlugRoute: typeof KateqoriyaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kataloq': {
      id: '/kataloq'
      path: '/kataloq'
      fullPath: '/kataloq'
      preLoaderRoute: typeof KataloqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kateqoriya/$slug': {
      id: '/kateqoriya/$slug'
      path: '/kateqoriya/$slug'
      fullPath: '/kateqoriya/$slug'
      preLoaderRoute: typeof KateqoriyaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KataloqRoute: KataloqRoute,
  KateqoriyaSlugRoute: KateqoriyaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
